repos:
  # For development test
  - repo: https://github.com/shenxianpeng/cpp-linter-hooks
    rev: latest
    hooks:
      - id: clang-format
        verbose: true
        args: [--style=Google, --version=13]
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        args: [--max-line-length=120]
