repos:
  # Start: for development testing
  - repo: https://github.com/shenxianpeng/cpp-linter-hooks
    rev: latest
    hooks:
      - id: clang-format
        verbose: true
        args: [--style=Google, --version=14]
      # - id: clang-tidy
      #   verbose: true
      #   args: [--checks="boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*"]
        # or specify the path of .clang-tidy
        # args: [--config-file=."]
  # End: for development testing
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        args: [--max-line-length=120]
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: bash -c "pip install . && pytest -v tests"
        description: Run all tests 
        language: system
        types: [python]