---
# This file tells https://pre-commit.com/ which hooks
# are provided by this repo for use by other git repos.

- id: clang-format
  name: clang-format
  description: Automatically run `clang-format` against C/C++ source code
  entry: clang-format-hook
  language: python
  files: \.(h\+\+|h|hh|hxx|hpp|c|cc|cpp|c\+\+|cxx)$
  types_or: [c, c++, c#, objective-c]

# - id: clang-tidy
#   name: clang-tidy
#   description: Run `clang-tidy` against C/C++ code to find warnings/errors
#   language: python
#   files: \.(h\+\+|h|hh|hxx|hpp|c|cc|cpp|c\+\+|cxx)$
#   types_or: [c, c++, c#, objective-c]
#   entry: clang-tidy

# - id: docker-clang-format
#   name: clang-format
#   description: Run `clang-format` against C/C++ source code in Docker container
#   language: docker
#   files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
#   entry: clang-format -i
#   args: ["-style=Google"]
  
# - id: docker-clang-tidy
#   name: clang-tidy
#   description: Run `clang-tidy` against C/C++ code to find warnings/errors in Docker container
#   language: docker
#   types_or: [c, c++, c#, objective-c]
#   entry: clang-tidy
