name: "Tag"

on:
  push:
    branches: main
    paths: '**.py'
  pull_request:
    branches: main
    paths: '**.py'
  workflow_dispatch:

jobs:
  add-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: retag latest commit for testing
        run: |
          git config user.name 'github-actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git push --delete origin latest || true
          git tag -a latest -m 'Retag latest commit'
          git push origin latest
